name: Deployment

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest tests/
        env:
          API_WEATHER_KEY: ${{ secrets.API_WEATHER_KEY }}
          SECRET_KEY: test
          DATABASE: test
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Generate module and provider bindings
        run: npm run get
      - name: Deploy
        run: npm run deploy
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          API_WEATHER_KEY: ${{ secrets.API_WEATHER_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE: data/database.db
          STRAVA_CLIENT_ID: ${{ vars.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_WEBHOOK_TOKEN: ${{ secrets.STRAVA_WEBHOOK_TOKEN }}
